stages:
- name: Build
  steps:
  - runScriptConfig:
      image: alpine
      shellScript: 
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: devstarter:${CICD_PIPELINE_ID}-${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34838
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
branch:
  include:
  - master
