stages:
- name: Build
  steps:
  - runScriptConfig:
      image: alpine
      shellScript: 
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: wunca38/test:${CICD_PIPELINE_ID}-${CICD_EXECUTION_SEQUENCE}
## internal registry
#      registry: 127.0.0.1:34838
## external registry
      pushRemote: true
      registry: docker-registry.eng.psu.ac.th
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
branch:
  include:
  - master
